version: "3.7"
services:
  app:
    build:
      args:
        user: cubic
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cubic
    container_name: cubic-app
    restart: unless-stopped
    working_dir: /var/www/html/cubic/
    volumes:
      - ./:/var/www/html/cubic
    networks:
      - cubic
    links:
      - db

  db:
    image: mysql:8.0
    container_name: cubic-db
    restart: unless-stopped
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - cubic

  nginx:
    image: nginx:alpine
    container_name: cubic-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/cubic
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - cubic

networks:
  cubic:
    driver: bridge